### ISSUE TITLE
Yax is new... feedback, please?

### ISSUE THREAD

**Issue by gudata** [gudata/yax_com#1]
@DanielKehoe would like feedback about yax.com.

Did deployment and editing work?

What are your thoughts, suggestions for improvements, etc.?

Just give a reply here.

_If you are curious about Yax, go to [stackless.community](https://stackless.community/) and sign up for the newsletter, all about Yax and building websites without frameworks or build tools._

**Comment by gudata** [comment]
Hi @DanielKehoe , 
It worked and I got the idea. 
When I saw the welcome page on my new website I got the appetite for more, so if you would like to see some next steps - how to make the deployed website more feature-rich would be nice. 
I have started wondering how to package/push some javascript/css/scss/hugo/jekil, then I have start wondering will work with some database providers out-there...and now I am wondering if I am using database am I still stackless :)

**Comment by DanielKehoe** [comment]
Thanks for the feedback! Glad you are inspired. For a more ferature-rich website, I'll soon build some more templates for Yax.com. You can do database access with vanilla JavaScript from a web component and that will be stackless. I recommend looking at Fauna DB, PostgREST, or Supabase for database access without a framework or ORM. If you go with Hugo and Jekyll you can get the benefits of JAMstack (free hosting and deploys from GitHub) but you will need build tools and template languages so not really stackless in that case. Look at stackbit.com for JAMstack.

Please keep in touch and let me know where you go with all this.
